### ISSUE TITLE
unable to parse apptoken

### ISSUE THREAD

**Issue by omski** [DeBaschdi/service.telerising#3]
Hi,

seit ca. einer Woche meckert die API und heute habe ich mal ins Log geschaut was los ist.
Dort sah ich folgende Fehlernachricht:

IGN_MAX: false
ERROR.... Unable to parse apptoken json data (trying old apptoken method now...)
INFO... LOGIN OK!
INFO... YOUR ACCOUNT TYPE: RESELLER

==== API STARTED! =====

Version 1.3.7 ist auf einen Raspy mit aktuellem Kodi installiert.

Ich verwende Telerising mit 1und1tv, den Server habe ich testweise auch schon gewechselt.

Habe gesehen die V 1.3.7 ist ja auch erst eine gute Woche raus... hat vllt was damit zu tun?

Merci und schöne Grüße!

**Comment by sunsettrack4** [comment]
Der Login ist okay, somit ist alles in Ordnung. 1und1 TV benutzt noch ein älteres Backend, damit funktioniert der neuere Zattoo Login-Prozess nicht.

**Comment by sunsettrack4** [comment]
@DeBaschdi Kann es sein, dass bei einem "Error" im Log eine Fehlermeldung in Kodi erscheint?

**Comment by omski** [comment]
Hab mal das Debug Log angemacht aber es ist auch damit nicht mehr zu sehen als das:

020-08-15 22:44:59.529 T:1823560560  NOTICE: [Telerising API 1.3.7] Machine is armv7l
2020-08-15 22:45:03.239 T:2665735024  NOTICE: Previous line repeats 2 times.
2020-08-15 22:45:03.575 T:1823560560  NOTICE: [Telerising API 1.3.7] Starting API....
2020-08-15 22:45:15.176 T:1823560560   ERROR: [Telerising API 1.3.7] Please check Telerising Logfile for Details

**Comment by DeBaschdi** [comment]
Ja, wenn ein "ERROR" im Log auftaucht, spuckt das Addon einen Fehler aus, ist zusätzlich "restart on failure" aktiviert, startet das Addon im loop neu durch....

**Comment by sunsettrack4** [comment]
Okay, somit funktioniert die API einwandfrei. Das Addon müsste die entsprechende Fehlermeldung ignorieren können, wenn der Login im zweiten Anlauf erfolgreich ist.

Der Prozess wurde geändert, da es leider unterschiedliche Backends bei den Resellern gibt und die API natürlich alle Varianten abdecken muss.

**Comment by DeBaschdi** [comment]
Wieso so kompliziert?
Da der Fehler keiner ist, reicht ein "Notice" als Logmeldung.
Das Addon soll bei einem echten "ERROR" stoppen bzw neu starten, finde ich praktisch.

**Comment by sunsettrack4** [comment]
Letztendlich ist ein fehlgeschlagener Login-Versuch ein Fehler. Ich habe die Meldung nun trotzdem abgeändert, schließlich ist der Login-Prozess ja in diesem Fall noch nicht komplett abgeschlossen.

Siehe: https://github.com/sunsettrack4/telerising/commit/f733127f2f7703afcf41db4efad5ea40c1d81320
Neue Version: 0.3.8

**Comment by omski** [comment]
Das die Kommunikation zum 1und1 Backend nicht (mehr) funktioniert ist mit der Version > 0.3.7 also normal?

**Comment by sunsettrack4** [comment]
Bitte ggf. das kommende Addon-Update abwarten, dann hat sich das Problem erledigt. Die Kommunikation zum 1und1-Backend funktioniert einwandfrei, es geht hierbei nur um das Zusammenspiel zwischen API und Kodi-Addon.

**Comment by omski** [comment]
V0.3.8 habe ich installiert aber das Problem besteht weiterhin.
Einzige Änderung: anstatt eines Errors wird nun INFO im Log ausgegeben.

**Comment by sunsettrack4** [comment]
Welches Problem besteht weiterhin? Es gibt keinen ERROR, somit sollte das Addon durchlaufen.

**Comment by omski** [comment]
Alles gut war mein Fehler. TvHeadend hat die API zum Laden der Playlist nicht erreicht aber das war ein Konfigurationsproblem und hatte nichts mit telerising zu tun.
Vielen Dank für den Support!
